datawarehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: data_warehouse
      port: 5432
      user: dwh_user
      password: "D@taW@rehou5e2025!S3cuRe"
      dbname: datawarehouse
      schema: public
      threads: 4
